version: "3.8"
services:
    flask:
        container_name: flask_app
        build: .
        ports:
            - "8000:8000"
        environment:
            - GOOGLE_APPLICATION_CREDENTIALS=/app/key.json
