version: "3.8"
services:
    flask:
        container_name: flask_app
        build: .
        ports:
            - "8000:8000"
        volumes:
            - "/Users/laura.jordana/Development/walkme-analytics/secrets/key.json:/app/key.json"
        environment:
            - GOOGLE_APPLICATION_CREDENTIALS=/app/key.json
