version: "3.8"
services:
    flask:
        container_name: flask_app
        depends_on:
            - "mongo"
        build: .
        ports:
            - "8000:8000"
        volumes:
            - "/Users/laura.jordana/Development/walkme-analytics/secrets/key.json:/app/key.json"
        environment:
            - GOOGLE_APPLICATION_CREDENTIALS=/app/key.json
    mongo:
        image: "mongo:latest"
        ports:
            - "27017:27017"
        volumes:
            - "/Users/laura.jordana/mongo-data:/data/db"
    # nginx:
    #     image: "nginx:latest"
    #     volumes:
    #         - "/Users/laura.jordana/nginx.conf:/etc/nginx/nginx.conf"
    #     ports:
    #         - "80:80"
    #         - "443:443"
